- name: Ensure Nginx is installed
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - reload nginx


- name: Copy Nginx site configuration
  template:
    src: my_site.j2
    dest: /etc/nginx/sites-available/my_site
  notify:
    - reload nginx


- name: Enable site configuration
  file:
    src: /etc/nginx/sites-available/my_site
    dest: /etc/nginx/sites-enabled/my_site
    state: link
  notify:
    - reload nginx


- name: Validate Nginx configuration
  command: nginx -t
  notify:
    - reload nginx

- name: Start and enable Nginx
  systemd:
    name: nginx
    enabled: true
    state: started
